import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ProductCategory from "@/app/_components/products/product-category";
import { Header } from './_components/header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      {/* <ProductCategory/> */}
      <body className={inter.className}>
      <Header />
        {children}
      </body>
    </html>
  );
}
